'use strict';

const settings = require('../services/settings');
const { esc, urduFontCss } = require('./common');
const { formatMoney, formatNumber, formatDate, formatDateTime } = require('../../shared/format.mjs');

function cellValue(col, v, currency) {
  if (v === null || v === undefined || v === '') return '';
  if (col.type === 'money') return formatMoney(v, currency);
  if (col.type === 'number') return formatNumber(v);
  return String(v);
}

/** A4 report page used for Print and Export PDF. */
function renderReport(report) {
  const b = settings.get('business');
  const currency = settings.get('general').currency || 'Rs.';
  const period = report.noDate ? `As of ${formatDateTime(new Date())}` : report.from === report.to ? formatDate(report.from) : `${formatDate(report.from)} – ${formatDate(report.to)}`;
  const head = report.columns.map((c) => `<th class="${c.type === 'text' ? 'l' : 'r'}">${esc(c.label)}</th>`).join('');
  const rows = report.rows
    .map((r) => `<tr class="${r.kind === 'head' ? 'sec' : r.bold ? 'bd' : ''}">${report.columns.map((c) => `<td class="${c.type === 'text' ? 'l' : 'r'}"><bdi>${esc(cellValue(c, r[c.key], currency))}</bdi></td>`).join('')}</tr>`)
    .join('');
  const totals = report.totals
    ? `<tr class="tot">${report.columns.map((c) => `<td class="${c.type === 'text' ? 'l' : 'r'}">${esc(cellValue(c, report.totals[c.key], currency))}</td>`).join('')}</tr>`
    : '';
  const cards = (report.cards || [])
    .map((c) => `<div class="card"><div class="cl">${esc(c.label)}</div><div class="cv">${esc(c.type === 'money' ? formatMoney(c.value, currency) : c.type === 'number' ? formatNumber(c.value) : c.value)}</div></div>`)
    .join('');
  return `<!doctype html><html><head><meta charset="utf-8"><title>${esc(report.title)}</title><style>
${urduFontCss()}
@page{size:A4;margin:12mm}
*{box-sizing:border-box}
body{font-family:'Segoe UI',Arial,'RPOS Urdu',sans-serif;font-size:11px;color:#111;margin:0}
.hdr{display:flex;justify-content:space-between;align-items:flex-end;border-bottom:2px solid #111;padding-bottom:6px;margin-bottom:10px}
.hdr h1{font-size:18px;margin:0}.hdr .biz{font-size:13px;font-weight:600}.muted{color:#555}
.cards{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:10px}
.card{border:1px solid #ccc;border-radius:6px;padding:6px 10px;min-width:120px}
.cl{font-size:10px;color:#555}.cv{font-size:14px;font-weight:700}
table{width:100%;border-collapse:collapse}
th{background:#f1f1f1;font-weight:600;border-bottom:1px solid #999;padding:5px 6px}
td{border-bottom:1px solid #e5e5e5;padding:4px 6px}
tr.sec td{background:#e9e4f5;font-weight:700;letter-spacing:.5px}
tr.bd td{font-weight:700}
tr.tot td{font-weight:700;border-top:2px solid #111;background:#fafafa}
.l{text-align:left}.r{text-align:right}
.note{margin-top:8px;font-size:10px;color:#555}
.foot{margin-top:14px;font-size:9px;color:#777;text-align:center}
</style></head><body>
<div class="hdr"><div><div class="biz"><bdi>${esc(b.name)}</bdi></div><h1>${esc(report.title)}</h1></div>
<div class="r"><div>${esc(period)}</div><div class="muted">Printed ${esc(formatDateTime(new Date()))}</div></div></div>
${cards ? `<div class="cards">${cards}</div>` : ''}
<table><thead><tr>${head}</tr></thead><tbody>${rows || `<tr><td colspan="${report.columns.length}" class="l muted">No data for this period.</td></tr>`}${totals}</tbody></table>
${report.note ? `<div class="note">${esc(report.note)}</div>` : ''}
<div class="foot">Generated by Retail POS</div>
</body></html>`;
}

/** CSV with UTF-8 BOM so Excel shows Urdu correctly. */
function renderCsv(report) {
  const q = (v) => {
    const s = v === null || v === undefined ? '' : String(v);
    return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
  };
  const lines = [report.columns.map((c) => q(c.label)).join(',')];
  for (const r of report.rows) lines.push(report.columns.map((c) => q(r[c.key])).join(','));
  if (report.totals) lines.push(report.columns.map((c) => q(report.totals[c.key])).join(','));
  return '﻿' + lines.join('\r\n');
}

module.exports = { renderReport, renderCsv };
